"use client";
import Link from "next/link";
import {useRef,useState} from "react";
import {VersionSelector} from "@/components/version-selector";
import {Icon} from "@/components/icon";
import {RECONSTRUCTION,V11_DISCLAIMER} from "@/lib/v11/fixtures";
import {scenarios,scenarioById} from "@/lib/v11/consolidated/fixtures";
import {evidenceFor,type Evidence} from "@/lib/v11/consolidated/types";
import {consolidate,memberships} from "@/lib/v11/consolidated/themes";
import {detect} from "@/lib/v11/consolidated/bottlenecks";
import {mapDenial} from "@/lib/v11/consolidated/denials";
import {prioritize} from "@/lib/v11/prioritized/ranking";
import {reference} from "@/lib/v11/prioritized/types";
import base from "./workspace.module.css";
import styles from "./consolidated-workspace.module.css";

export function ConsolidatedWorkspace({view}:{view:"themes"|"denials"}){
 const [id,setId]=useState("mixed"),[source,setSource]=useState<Evidence|null>(null);
 const dialog=useRef<HTMLDialogElement>(null);
 const scenario=scenarioById(id),bottlenecks=detect(scenario.rows),themes=consolidate(scenario,bottlenecks.groups),mapping=mapDenial(scenario.rows),ranked=prioritize(scenario.rows);
 const title=view==="themes"?"Capacity Themes":"Denials & Bottlenecks";
 const sourceLink=(row:Evidence)=><a href={"#source-"+row.id}>{reference(row)}</a>;
 return <div className={base.workspace}>
  <a className="skip-link" href="#m06-main">Skip to content</a>
  <header className={base.header}><Link href="/v1-1" className={base.brand}>neverlost<span>.</span></Link><span>V1.1 / RECONSTRUCTION · M06</span></header>
  <main id="m06-main" className={base.main}>
   <VersionSelector current="v11"/>
   <div className="page-heading"><div><p className="eyebrow">V1 CONCEPTS / RECOVERED V1.1 EXTENSION</p><h1>{title}</h1><p className="page-description">Trace the grouping. Inspect the trigger. Keep the limits visible.</p></div></div>
   <div className="disclaimer" role="note"><Icon name="info"/><p>{V11_DISCLAIMER}</p></div><p className={base.reconstruction}>{RECONSTRUCTION}</p>
   <nav className={base.navigation} aria-label="V1.1 surfaces">{[["/v1-1","Source Authority / Evidence"],["/v1-1/run-review","Run Review"],["/v1-1/prioritized-evidence","Prioritized Evidence"],["/v1-1/capacity-themes","Capacity Themes"],["/v1-1/denials-bottlenecks","Denials & Bottlenecks"]].map(([url,label])=><Link href={url} key={url} aria-current={label===title?"page":undefined}>{label}</Link>)}</nav>
   <section className="concept-intro panel"><p className="eyebrow">CHANGED FROM V1</p><h2>{view==="themes"?"From windows to reviewable themes.":"The V1 bottleneck concept, extended."}</h2><p>V1 already represented capacity windows and bottlenecks. Recovered V1.1 added consolidation, source-sensitive handling and relationships to prioritized evidence and payer-denial context. This is an evolution of that analytical prototype, not a separate product.</p><p>Grouping does not deduplicate evidence, establish sustained capacity, prove improvement or decline, or determine clinical significance, disability/work capacity, medical necessity or eligibility.</p></section>
   <section className={base.scenario} aria-label="M06 scenario"><label htmlFor="m06-scenario">Synthetic M06 scenario</label><select id="m06-scenario" value={id} onChange={e=>setId(e.target.value)}>{scenarios.map(s=><option key={s.id} value={s.id}>{s.title}</option>)}</select><p>{scenario.description}</p><small>Independent synthetic fixtures. Selection resets on reload or navigation; no saved state.</small></section>
   <div className={styles.notice} role="status">{mapping?"Payer-denial source present · heuristic source label; human review required.":"No payer-denial source supplied · no insurance/authorization bottleneck or denial mapping."}</div>
   {view==="themes"?<>
    <details className={base.changeNote}><summary>Recovered membership and limit rules</summary><p>Lowercase substring matching across intervention, source evidence, what became possible and learning. Every matching family receives the window once; no evidence deduplication occurs. No match falls back to treatment response/carryover, without proving a response.</p><p>Groups sort by window count descending; ties retain first-seen group order. The classifier defines eight families. The recovered ten-theme guard is preserved but structurally unreachable from those eight families. Tests of that guard use artificial groups only.</p><p>Source-document and authority lists are unique display inventories, not deduplicated evidence. Related bottlenecks use broad keyword rules and are limited to three; a link is not a causal conclusion.</p></details>
    <p className={base.result}>{scenario.windows.length} windows · {themes.length} themes · 8 recovered families · output guard 10</p>
    {!themes.length&&<section className={base.empty}><h2>No capacity themes</h2><p>No input windows; no capacity inference.</p></section>}
    <div className={base.cards}>{themes.map((theme,index)=><article className="panel" key={theme.name} aria-label={theme.name}><div className={styles.card}><p className="eyebrow">THEME {index+1} / MEMBERSHIP, NOT OUTCOME</p><h2>{theme.name}</h2><p>{theme.members.length} contributing window(s)</p><dl className={styles.fields}><div><dt>Documents</dt><dd>{theme.documents.join("; ")}</dd></div><div><dt>Source-authority mix · supplied labels</dt><dd>{theme.authorities.join("; ")}</dd></div><div><dt>Interpretation</dt><dd>A keyword-based grouping of candidate windows. No measured functional change or retained gains is established.</dd></div></dl><p>Related candidate bottlenecks: {theme.related.length?theme.related.map((b,i)=><span key={b.id}>{i>0?"; ":""}<a href={"#bottleneck-"+b.id}>{b.title}</a></span>):"No link identified."}</p>
     <details><summary>Contributing windows for {theme.name}</summary>{theme.members.map(m=>{const row=evidenceFor(scenario,m.window.evidenceId);return <div className={styles.member} key={m.window.id}><h3><a href={"#window-"+m.window.id}>{m.window.id}</a></h3><p>{m.basis}</p><p>Evidence {row.id}: {sourceLink(row)}</p></div>;})}</details>
    </div></article>)}</div>
    <section className={base.reviewSection} aria-label="Capacity window inventory"><h2>Capacity window inventory</h2>{scenario.windows.map(w=><article id={"window-"+w.id} key={w.id} className={base.empty} aria-label={w.id}><h3>{w.id}</h3><dl className={styles.fields}>{[["Intervention · synthetic input",w.intervention],["Window source-evidence text · synthetic input",w.sourceEvidence],["What became possible · candidate input",w.possible||"Not supplied"],["Learning · candidate input",w.learning||"Not supplied"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p>Membership: {memberships(w).map(m=>m.name).join("; ")}</p><p>Underlying source evidence: {sourceLink(evidenceFor(scenario,w.evidenceId))}</p><p>Window text is an invented analytical input, not a measured outcome or a verbatim source quotation.</p></article>)}</section>
   </>:<>
    <details className={base.changeNote}><summary>Recovered denial and bottleneck rules</summary><p>Eight category rules consolidate matching evidence, in recovered category order. Source rows sort by existing evidence-strength input; the six-key-source display limit and eight-bottleneck output guard are preserved.</p><p>Only exact payer-denial source type triggers the insurance category. Only exact claimant disability-appeal type triggers the appeal category. Mentions of denial, appeal, providers or therapy do not change source authority.</p><p>Mapping correction: without an actual classified denial source, this reconstruction returns no mapping. The historical code could return a truthy mapping object without a denial. This is an explicit correction, not historical parity.</p></details>
    <section className={base.reviewSection} aria-label="Denial source mapping"><h2>Denial source mapping</h2>{!mapping?<p>No denial mapping created. Absence is not an eligibility or coverage conclusion.</p>:<>
     <dl className={styles.fields}>{[["Payer",mapping.payer||"Not identified"],["Requested / denied service",mapping.service||"Not identified"],["Denial context",mapping.context||"Not identified"]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
     <p>All contributing payer sources: {mapping.sources.map((row,i)=><span key={row.id}>{i?"; ":""}{sourceLink(row)}</span>)}</p><p>Recovered behavior joins denial facts and takes the first available payer/service/context fields. With multiple sources these can cross document boundaries; this is not a separate mapping per denial.</p>
     {!mapping.service&&<p>Requested-service keyword fallback: {mapping.servicePhrase?.excerpt||"Not detected; human inspection required."} This excerpt is not an authenticated service label.</p>}
     <div className={base.cards}>{mapping.rationale.map(item=><article className={base.empty} key={item.label}><h3>{item.label}</h3>{item.result?<><p>Matched substring: {item.result.term}</p><blockquote>{item.result.excerpt}</blockquote></>:<p>Not detected; human inspection required.</p>}</article>)}</div>
     <p>Keyword detection does not confirm actual criteria, missing items, rights or dates. Negated or incomplete wording can still match.</p>
     {(["provider","ot"] as const).map(kind=><section key={kind} className={base.reviewSection} aria-label={kind==="ot"?"Candidate OT support":"Candidate provider support"}><h3>{kind==="ot"?"Candidate OT support":"Candidate provider support"}</h3><p>Exact source-type and substring matches, ranked with unchanged M05 rules; at most 10 per source class. These are candidates, not criteria satisfaction.</p>{mapping[kind].length?<ul>{mapping[kind].map(m=><li key={m.row.id}>{sourceLink(m.row)}<p>Matched {m.hits.join(", ")} · heuristic score {m.score}</p></li>)}</ul>:<p>No matching supporting evidence supplied.</p>}</section>)}
     <p>PT and claimant sources are not included in these two recovered mapping selectors, even when their text looks relevant. They remain inspectable in the source inventory.</p>
     <h3>Unresolved information</h3><ul>{mapping.gaps.map(g=><li key={g}>{g}</li>)}<li>Actual criteria and source suitability require human inspection; keyword matches do not resolve them.</li><li>Rights/deadline and any sustained daily-function change remain unverified.</li></ul>
    </>}</section>
   </>}
   <section className={base.reviewSection} aria-label="Candidate bottlenecks"><h2>Candidate bottlenecks · V1.1 extension</h2><p>{bottlenecks.rawCount} evidence/category matches · {bottlenecks.groups.length} consolidated candidates · maximum 8</p>{!bottlenecks.groups.length&&<p>No candidate bottlenecks from the supplied evidence.</p>}
    <div className={base.cards}>{bottlenecks.groups.map(group=><article className="panel" id={"bottleneck-"+group.id} key={group.id} aria-label={group.title}><div className={styles.card}><h3>{group.title}</h3><p>Why this appeared: {group.id==="insurance"?"exact insurance denial letter source type":group.id==="appeal"?"exact disability appeal source type":"domain overlap: "+group.domains.join(", ")}.</p><p>Source-sensitive context: {group.summary}.</p><p>Unresolved / needed: {group.needed}</p><p>Historical confidence heuristic: {group.confidence} — not calibrated reliability or validation.</p><details><summary>Triggering evidence for {group.title}</summary><ul>{group.rows.map(row=><li key={row.id}>{sourceLink(row)}<p>Source type: {row.source.type} · matched domains: {row.domains.filter(d=>group.domains.some(g=>g===d)).join(", ")||"source-type condition"} · supplied strength {row.strength}</p></li>)}</ul><p>Recovered key-source summary (maximum six): {group.sources.join("; ")}</p></details></div></article>)}</div>
   </section>
   <section className={base.reviewSection} aria-label="Source evidence inventory"><h2>Source evidence & M05 relationship</h2><p>Unchanged M05 ranking rules are evaluated on this M06 fixture set. These memberships do not refer to M05’s separate demo scenarios. <Link href="/v1-1/prioritized-evidence">Inspect the Prioritized Evidence surface</Link> (navigation resets the scenario).</p>
    <div className={base.cards}>{scenario.rows.map(row=>{const rank=ranked.find(r=>r.row.id===row.id);return <article className="panel" id={"source-"+row.id} aria-label={row.id} key={row.id}><div className={styles.card}><h3>{row.id}</h3><p>{reference(row)}</p><p>{row.source.type} · {row.source.authority}</p><dl className={styles.fields}><div><dt>Source observation · synthetic</dt><dd>{row.fact}</dd></div><div><dt>Interpretation · synthetic</dt><dd>{row.consequence}</dd></div></dl><p>M05 rules on this fixture: candidate rank {rank?.rank}, score {rank?.total}, {rank?.selected?"selected":"excluded"}. {rank?.reason}</p><button className="primary-button" onClick={()=>{setSource(row);dialog.current?.showModal();}} aria-label={"Inspect source "+row.id}>Inspect source <Icon name="source" width="16" height="16"/></button></div></article>;})}</div>
   </section>
   <footer className={base.footer}><strong>M06 boundary</strong><p>New deterministic reconstruction, not historical UI. No final synthesis, packets, appeal generation/submission, AI, autonomous actions, approval state, persistence, uploads or external communication. Five-report applied workflows remain separate.</p><p>Generic summary prose is deliberately bounded; historical statements about improvement, OCR success and next actions are not presented as demonstrated results. See the M06 notes for deviations.</p></footer>
  </main>
  <dialog ref={dialog} className="detail-dialog" aria-labelledby="m06-dialog-title"><div className="dialog-header"><span className="eyebrow">M06 / SYNTHETIC PROVENANCE</span><button className="close-button" aria-label="Close source dialog" onClick={()=>dialog.current?.close()}><Icon name="close"/></button></div><h2 id="m06-dialog-title">Synthetic source inspection</h2>{source&&<><div className="source-quote"><blockquote>{source.source.excerpt}</blockquote></div><dl className="provenance-fields">{[["Evidence ID",source.id],["Document",source.source.document],["Page",String(source.source.page)],["Chunk",source.source.chunk],["Source type",source.source.type],["Authority · supplied label",source.source.authority]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="dialog-footnote">All content is independently invented. Classification, grouping, mapping and ranking are not authenticated provenance or professional judgment.</p></>}</dialog>
 </div>;
}
